version: "3.8"

services:
  mongodb:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - DB_HOST=mongodb
      - DB_PORT=27017
    image: 'cats_backend'
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  cats-app-front:
    build:
      context: ./cats-app-front
      dockerfile: Dockerfile
    ports: 
      - 4201:4201
    image: cats-app-front
    volumes: 
      - ./cats-app-front:/usr/local/app/cats-app-front
      - /usr/local/app/cats-app-front/node_modules
    depends_on:
      - app
